# Generated by Django 2.2.10 on 2020-12-18 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20201218_1822'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'permissions': {('is_employee', 'Is employee')}},
        ),
    ]
