# Generated by Django 2.2.10 on 2020-12-19 02:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('menu', '0004_auto_20201218_2052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'permissions': {('is_nora', 'Is nora')}},
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('date', models.DateField()),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Meal')),
            ],
        ),
    ]
