# Generated by Django 2.2.10 on 2020-12-19 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_remove_choice_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='meal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.Meal'),
        ),
        migrations.AddField(
            model_name='choice',
            name='note',
            field=models.TextField(null=True),
        ),
    ]
