# Generated by Django 2.2.10 on 2020-12-19 22:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0007_auto_20201219_1759'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='choice',
            unique_together={('date', 'user')},
        ),
    ]
